package com.joeldietz.resourcy.models;

import java.net.URL;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import com.google.appengine.api.datastore.Link;
import com.google.appengine.repackaged.org.joda.time.DateTime;

public class Category {
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long Id;

	private String name;
	
	private Boolean official; // official categories have keys and can be managed.
	private Long key; // must be autogenerated and "secret"
	
	private String officialWaveId;
	private String officialWaveletId;
	private String officialDomain;
	
	private String updateInterval; // perhaps refers to a task queue 
	
	private DateTime lastUpdatedByServer;
	private DateTime lastModifiedByUser;
	private Long superCatId;
	 
	private Link url;   // could be a blog url
	
	
	
	//Resouces  
	
	private Long ownerKey; 
	

}
